#!/bin/tcsh

source /etc/profile.d/modules.csh

setenv LC_ALL "C"
set path = `echo $path | tr ' ' '\n' | grep -v '/ifs/home/'`
set path = ( ./code/code.main $path )

umask 007

source inputs/params/params.tcsh


