#!/bin/tcsh
#$ -S /bin/tcsh
source ./code/code.main/custom-tcshrc    # customize shell environment

##
## USAGE: scripts-qsub-run JOB-PREFIX N-THREADS MEMORY SCRIPT-PATH ARGS ...
##

if ($#argv < 4) then
  grep '^##' $0
  exit
endif

set jpref = $1
set nthreads = $2
set mem = $3
set prog = $4
shift
shift
shift
shift

#scripts-send2err $jpref

#exit

if (-e $jpref.sh) then
  scripts-send2err "Error: [scripts-qsubmem-run] $jpref.sh already exists, cannot overwrite."
  exit 1
endif

#set tmp_resources = `echo 10000/$nthreads | bc`                                     # /tmp space per thread in Mbytes
#set qsub_params = "-l tmp_free=${tmp_resources}M -l tmp_token=${tmp_resources}M"
 
#qsub -q all.q -cwd $qsub_params -l mem_free=$mem -l h_vmem=$mem -l mem_token=$mem -o :$jpref.out -e :$jpref.err -pe threaded $nthreads $jpref.sh >! $jpref.jid

echo '#\!/bin/tcsh' >! $jpref.sh
echo '#'SBATCH --time=24:00:00 >> $jpref.sh
echo '#'SBATCH -n 1 >> $jpref.sh
echo '#'SBATCH -c $nthreads >> $jpref.sh
echo '#'SBATCH -o $jpref.out >> $jpref.sh
echo '#'SBATCH -e $jpref.err >> $jpref.sh
echo '#'SBATCH --mem=$mem >> $jpref.sh

scripts-print-cmdline $prog $argv:q >> $jpref.sh

sbatch $jpref.sh >! $jpref.jid

cat $jpref.jid | cut -d' ' -f4





