#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: run [--dry-run]
##

#% <ADD DESCRIPTION>

# process command-line inputs
if ($#argv > 1) then
  grep '^##' $0 | scripts-send2err
  exit
endif

set opt = "$1"

# setup
set op = %%op%%
set inpdirs = "inpdirs/*"             # indicate input directories
set filter = ""                       # filter input objects
set results = results
scripts-create-path $results/
scripts-send2err "=== Operation = $op ============="
set resources = %%cpu_threads%%,%%cpu_memory%%,%%cpu_time%%
set cmd = "./code/code.main/scripts-qsub-wrapper $resources ./code/hicseq-$op.tcsh"

# generate run script
Rscript ./code/code.main/pipeline-master-explorer.r -v -F "$filter" "$cmd" $results/$op "params/params.*.tcsh" "$inpdirs" "" "." 1

# run and wait until done!
set max_jobs = 50
if ("$opt" != "--dry-run") scripts-submit-jobs ./$results/.db/run $max_jobs



