#!/bin/tcsh
source ./code/code.main/custom-tcshrc     # shell settings

##
## USAGE: run [--dry-run]
##

#% This step performs pair-wise comparisons of sparse matrices.
#% TABLES: 
#% FIGURES:

if ($#argv > 1) then
  grep '^##' $0 | scripts-send2err
  exit
endif

set opt = "$1"

# setup
set op = matrix-sparse-diff
set inpdirs = "inpdirs/*"
set results = results
scripts-create-path $results/
scripts-send2err "=== Operation = $op ============="
set resources = 1,1G,24
set cmd = "./code/code.main/scripts-qsub-wrapper $resources ./code/hicseq-$op.tcsh"

# generate run script
Rscript ./code/code.main/pipeline-master-explorer.r -v "$cmd" $results/$op "params/params.*.tcsh" "$inpdirs" "" "." 2

# run and wait until done!
set max_jobs = 5    # $pipeline_max_jobs
if ("$opt" != "--dry-run") scripts-submit-jobs ./$results/.db/run $max_jobs


