#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: run [--dry-run]
##

#% <ADD DESCRIPTION>

# process command-line inputs
if ($#argv > 1) then
  grep '^##' $0 | scripts-send2err
  exit
endif

set opt = "$1"

# setup
set op = hubs-stats
set inpdirs = "inpdirs/loops"             # indicate input directories
set filter = ""                       # filter input objects
set results = results
scripts-create-path $results/
scripts-send2err "=== Operation = $op ============="
set resources = 1,10G,3
set cmd = "./code/code.main/scripts-qsub-wrapper $resources ./code/hicseq-$op.tcsh"

# generate run script
Rscript ./code/code.main/pipeline-master-explorer.r -v -F "$filter" --include-obj="loucy-hichip-Arima-1M" "$cmd" $results/$op "params/params.*.tcsh" "$inpdirs" "" "sample group" 1

# run and wait until done!
if ("$opt" != "--dry-run") scripts-submit-jobs ./$results/.db/run $pipeline_max_jobs
