#!/bin/tcsh

##
## USAGE: run
##

if ($#argv != 0) then
  grep "^##" $0
  exit
endif

# Set parameters
source ./params/params_report.tcsh
set genome = `cat ../pipeline/align/results/align.by_sample.bowtie2/*/job.vars.tsv | fgrep "genome" | fgrep -v "index" | sort -k1 | uniq | awk '{print $2}'`
set main_branch = filter.by_sample.mapq_$mapq/align.by_sample.$aligner/
set bscore_method = activity_500kb
set user = $USER
if ($transferGdrive == "TRUE") then
	set gdrive_remote = "$gdrive_remote_path""$report"
endif

#########################################################################################
#                                  MAIN CODE BELOW                                      #
#########################################################################################

rm -rf $report
mkdir $report


### TRACKS ###
if ("$tracks_bysample" == "TRUE") then
cd $report
ln -sf ../../pipeline/tracks/results/tracks.by_sample.juicer/${main_branch} hicfiles-juicer-by-sample
cd ..
endif

if ("$tracks_bygroup" == "TRUE") then
cd $report
ln -sf ../../pipeline/tracks/results/tracks.by_group.juicer/${main_branch} hicfiles-juicer-by-group
cd ..
endif


### STANDARD ###
if ("$standard" == "TRUE") then

#filter-stats
cp ../pipeline/filter-stats/results/filter-stats.standard/$main_branch/all-samples/counts.pdf $report/read-counts-classification.pdf
cp ../pipeline/filter-stats/results/filter-stats.standard/$main_branch/all-samples/percent.pdf $report/read-percentages-classification.pdf

#compartments-stats
cp ../pipeline/compartments-stats/results/compartments-stats.standard/compartments.by_sample.homer.res_${compBinSize}kb/filter.by_sample.mapq_20/align.by_sample.bowtie2/all-samples/*.pdf $report/

#matrix-stats
cp ../pipeline/matrix-stats/results/matrix-stats.standard/matrix-ic.by_group.cutoff_0/matrix-filtered.by_group.res_${binsize}kb/$main_branch/all-samples/stats.pdf $report/read-average-by-distance_byGroup.pdf
cp ../pipeline/matrix-stats/results/matrix-stats.standard/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/$main_branch/all-samples/stats.pdf $report/read-average-by-distance_bySample.pdf

#boundary-scores
cp ../pipeline/boundary-scores-pca/results/boundary-scores-pca.standard/boundary-scores.by_sample.$bscore_method/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/$main_branch/all-samples/pca.intra-left.k=001.pdf $report/pca-by-activity.pdf
cp ../pipeline/boundary-scores-pca/results/boundary-scores-pca.standard/boundary-scores.by_sample.$bscore_method/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/$main_branch/all-samples/pca.ratio.k=001.pdf $report/pca-by-insulation-score.pdf

#domains-stats
cp ../pipeline/domains-stats/results/domains-stats.standard/domains.by_group.hicratio.d_0500/matrix-ic.by_group.cutoff_0/matrix-filtered.by_group.res_${binsize}kb/$main_branch/all-samples/domains-stats.k=001.pdf $report/domains-stats_byGroup.pdf
cp ../pipeline/domains-stats/results/domains-stats.standard/domains.by_sample.hicratio.d_0500/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/$main_branch/all-samples/domains-stats.k=001.pdf $report/domains-stats_bySample.pdf

#compare-boundaries
cp ../pipeline/compare-boundaries-stats/results/compare-boundaries-stats.standard/compare-boundaries.by_group.standard/domains.by_group.hicratio.d_0500/matrix-ic.by_group.cutoff_0/matrix-filtered.by_group.res_${binsize}kb/$main_branch/all-samples/correlograms.pdf $report/correlograms_byGroup.pdf
cp ../pipeline/compare-boundaries-stats/results/compare-boundaries-stats.standard/compare-boundaries.by_sample.standard/domains.by_sample.hicratio.d_0500/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/$main_branch/all-samples/correlograms.pdf $report/correlograms_bySample.pdf

cd $report

#compartments
ln -sf ../../pipeline/compartments/results/compartments.by_group.homer.res_${compBinSize}kb/${main_branch} compartments-by-group
ln -sf ../../pipeline/compartments/results/compartments.by_sample.homer.res_${compBinSize}kb/${main_branch} compartments-by-sample

#compartments-stats
ln -sf ../../pipeline/compartments-stats/results/compartments-stats.standard/compartments.by_sample.homer.res_${compBinSize}kb/${main_branch}/all-samples/ compartments-stats-by-sample
ln -sf ../../pipeline/compartments-stats/results/compartments-stats.standard/compartments.by_group.homer.res_${compBinSize}kb/${main_branch}/all-samples/ compartments-stats-by-group

#boundary-scores
mkdir boundary-scores
cp ../../pipeline/boundary-scores-pca/results/boundary-scores-pca.standard/boundary-scores.by_sample.activity_500kb/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/${main_branch}/all-samples/matrix.ratio.k\=001.tsv boundary-scores/matrix.insulation.scores.tsv 
cp ../../pipeline/boundary-scores-pca/results/boundary-scores-pca.standard/boundary-scores.by_sample.activity_500kb/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/${main_branch}/all-samples/matrix.intra-left.k\=001.tsv boundary-scores/matrix.activity.scores.tsv

#domains
ln -sf ../../pipeline/domains/results/domains.by_group.hicratio.d_0500/matrix-ic.by_group.cutoff_0/matrix-filtered.by_group.res_${binsize}kb/${main_branch} domains
cd ..
endif

### HICPLOTTER-DIFF ###
if ("$hicplotter_bygroup" == "TRUE") then
cd $report
mkdir -p hicplotter-diff
mkdir -p hicplotter-diff/by_group/
ln -sf ../../pipeline/hicplotter-diff/results/hicplotter-diff.by_group.hicratio-selected-regions/matrix-ic.by_group.cutoff_0/matrix-filtered.by_group.res_${binsize}kb/${main_branch} hicplotter-diff/by_group
rm -f hicplotter-diff/by_group/*/job* hicplotter-diff/by_group/*/*.png
cd ..
endif

if ("$hicplotter_bysample" == "TRUE") then
cd $report
mkdir -p hicplotter-diff
mkdir -p hicplotter-diff/by_sample/
ln -sf ../../pipeline/hicplotter-diff/results/hicplotter-diff.by_sample.hicratio-selected-regions/matrix-ic.by_sample.cutoff_0/matrix-filtered.by_sample.res_${binsize}kb/${main_branch} hicplotter-diff/by_sample
rm -f hicplotter-diff/by_sample/*/job* hicplotter-diff/by_sample/*/*.png
cd ..
endif


### LOOPS ###
#loops
if ("$include_loops" == "TRUE") then
	cd $report
	mkdir loops
	cd loops
	ln -sn ../../../pipeline/loops/results/* ./
	cd ../../
endif

#loops-diff
if ("$include_loops_diff" == "TRUE") then
	cd $report
	mkdir loops-diff
	cd loops-diff
	ln -sn ../../../pipeline/loops-diff/results/* ./
	cd ../../
endif

#### DOMAINS-DIFF ### (create tex-templates for the selected comparisons)

#BY GROUP
if ("$activity_bygroup" == "TRUE") then
cd $report
mkdir -p domains-diff

foreach intraTAD_method ($intraTAD_methods)
	mkdir -p domains-diff/"${intraTAD_method}"
	
	foreach norm_method ($norm_methods)
		mkdir -p domains-diff/"${intraTAD_method}"/"${norm_method}"
		set comparisons_group = `ls ../../pipeline/domains-diff/results/domains-diff.by_group."$caller".d_0500."$norm_method"."$intraTAD_method"/matrix-"$matrix".by_group.cutoff_0/matrix-filtered.by_group.res_"$binsize"kb/filter.by_sample.mapq_"$mapq"/align.by_sample."$aligner"/`
		
		foreach comparison ($comparisons_group)
			mkdir -p domains-diff/"${intraTAD_method}"/"${norm_method}"/"${comparison}"
			set plotPath = domains-diff/"${intraTAD_method}"/"${norm_method}"/"${comparison}"

			foreach plot (final_results_volcano_TADs.png final_results_mean-TAD_activity.png final_results_scatter_meanTadActivity.pdf)
			cp ../../pipeline/domains-diff/results/domains-diff.by_group."${caller}".d_0500."${norm_method}"."${intraTAD_method}"/matrix-"${matrix}".by_group.cutoff_0/matrix-filtered.by_group.res_"${binsize}"kb/"${main_branch}"/"${comparison}"/"${plot}" "${plotPath}"/
			cp ../../pipeline/domains-diff/results/domains-diff.by_group."${caller}".d_0500."${norm_method}"."${intraTAD_method}"/matrix-"${matrix}".by_group.cutoff_0/matrix-filtered.by_group.res_"${binsize}"kb/"${main_branch}"/"${comparison}"/final_results* "${plotPath}"/
			end
		end
	end
end

# generate intraTAD templates
foreach intraTAD_method ($intraTAD_methods)
	foreach norm_method ($norm_methods)
		foreach comparison ($comparisons_group)			
                        set plotPath = domains-diff/"${intraTAD_method}"/"${norm_method}"/"${comparison}"
                        cp ../report-repo/tex-templates/template_intraTAD.tex $plotPath/template_intraTAD_tmp.tex
                        sed 's/REPORT_NAME/'${report}'/g' $plotPath/template_intraTAD_tmp.tex > $plotPath/template_intraTAD_tmp1.tex
                        sed 's/INTRATAD_METHOD/'${intraTAD_method}'/g' $plotPath/template_intraTAD_tmp1.tex > $plotPath/template_intraTAD_tmp2.tex
                        sed 's/NORM_METHOD/'${norm_method}'/g' $plotPath/template_intraTAD_tmp2.tex > $plotPath/template_intraTAD_tmp3.tex
                        sed 's PLOT_PATH '${plotPath}' g' $plotPath/template_intraTAD_tmp3.tex > $plotPath/template_intraTAD.tex
                        rm -f $plotPath/template_intraTAD_tmp*.tex
                end
        end
end
cd..
endif


#BY SAMPLE
if ("$activity_bysample" == "TRUE") then
cd $report
mkdir -p domains-diff

foreach intraTAD_method ($intraTAD_methods)
	mkdir -p domains-diff/"${intraTAD_method}"
	
	foreach norm_method ($norm_methods)
		mkdir -p domains-diff/"${intraTAD_method}"/"${norm_method}"
		set comparisons_group = `ls ../../pipeline/domains-diff/results/domains-diff.by_sample."$caller".d_0500."$norm_method"."$intraTAD_method"/matrix-"$matrix".by_sample.cutoff_0/matrix-filtered.by_sample.res_"$binsize"kb/filter.by_sample.mapq_"$mapq"/align.by_sample."$aligner"/`
		
		foreach comparison ($comparisons_group)
			mkdir -p domains-diff/"${intraTAD_method}"/"${norm_method}"/"${comparison}"
			set plotPath = domains-diff/"${intraTAD_method}"/"${norm_method}"/"${comparison}"

			foreach plot (final_results_volcano_TADs.png final_results_mean-TAD_activity.png final_results_scatter_meanTadActivity.pdf)
			cp ../../pipeline/domains-diff/results/domains-diff.by_sample."${caller}".d_0500."${norm_method}"."${intraTAD_method}"/matrix-"${matrix}".by_sample.cutoff_0/matrix-filtered.by_sample.res_"${binsize}"kb/"${main_branch}"/"${comparison}"/"${plot}" "${plotPath}"/
			cp ../../pipeline/domains-diff/results/domains-diff.by_sample."${caller}".d_0500."${norm_method}"."${intraTAD_method}"/matrix-"${matrix}".by_sample.cutoff_0/matrix-filtered.by_sample.res_"${binsize}"kb/"${main_branch}"/"${comparison}"/final_results* "${plotPath}"/
			end
		end
	end
end

# generate intraTAD templates
foreach intraTAD_method ($intraTAD_methods)
	foreach norm_method ($norm_methods)
		foreach comparison ($comparisons_group)			
                        set plotPath = domains-diff/"${intraTAD_method}"/"${norm_method}"/"${comparison}"
                        cp ../report-repo/tex-templates/template_intraTAD.tex $plotPath/template_intraTAD_tmp.tex
                        sed 's/REPORT_NAME/'${report}'/g' $plotPath/template_intraTAD_tmp.tex > $plotPath/template_intraTAD_tmp1.tex
                        sed 's/INTRATAD_METHOD/'${intraTAD_method}'/g' $plotPath/template_intraTAD_tmp1.tex > $plotPath/template_intraTAD_tmp2.tex
                        sed 's/NORM_METHOD/'${norm_method}'/g' $plotPath/template_intraTAD_tmp2.tex > $plotPath/template_intraTAD_tmp3.tex
                        sed 's PLOT_PATH '${plotPath}' g' $plotPath/template_intraTAD_tmp3.tex > $plotPath/template_intraTAD.tex
                        rm -f $plotPath/template_intraTAD_tmp*.tex
                end
        end
end
cd ..
endif



if ("$standard" == "TRUE" || "$activity_bygroup" == "TRUE" || "$activity_bysample" == "TRUE") then
### CONCATENATE TEMPLATES ###
cd $report
cp ../report-repo/tex-templates/template_standard.tex template_standard_custom.tex	
sed -i 's/REPORT_NAME/'${report}'/g' template_standard_custom.tex
cp ../report-repo/tex-templates/template_end.tex template_end_custom.tex	
sed -i 's/REPORT_NAME/'${report}'/g' template_end_custom.tex
cp ../report-repo/tex-templates/template_intro.tex  template_intro_custom.tex

if ("$aligner" == "bowtie2") then
	sed -i 's/ALIGNER_TOOL/bowtie2/g' template_end_custom.tex
	sed -i "s/ALIGNMENT_FILTER_PARAMS/--very-sensitive-local --local; mapq="$mapq"; --min-dist "$mindist" --max-offset 500./g" template_end_custom.tex
else
	sed -i 's/ALIGNER_TOOL/bwa/g' template_end_custom.tex
	sed -i "s/ALIGNMENT_FILTER_PARAMS/-A1 -B4 -E50 -L0; mapq="$mapq"; --min-dist "$mindist" --max-offset 500./g" template_end_custom.tex
endif

if ("$standard" == "TRUE" && ("$activity_bygroup" == "TRUE" || "$activity_bysample" == "TRUE")) then
echo "first
	cat template_intro_custom.tex template_standard_custom.tex domains-diff/*/*/*/template_intraTAD.tex template_end_custom.tex > full_template_custom.tex
else if ("$standard" == "TRUE" && "$activity_bygroup" == "FALSE" && "$activity_bysample" == "FALSE") then
echo "second"
	cat template_intro_custom.tex template_standard_custom.tex template_end_custom.tex > full_template_custom.tex
else if ("$standard" == "FALSE" && ("$activity_bygroup" == "TRUE" || "$activity_bysample" == "TRUE")) then
echo "third"
    	cat template_intro_custom.tex domains-diff/*/*/*/template_intraTAD.tex template_end_custom.tex > full_template_custom.tex
endif


# filter standard report by sample/group (if required)
if ("$standard_bysample" == "FALSE") then
	cat full_template_custom.tex | fgrep -v "%isSAMPLE" > p.tex
	rm full_template_custom.tex
	mv p.tex full_template_custom.tex
endif

if ("$standard_bygroup" == "FALSE") then
	cat full_template_custom.tex | fgrep -v	"%isGROUP" > p.tex
	rm full_template_custom.tex
	mv p.tex full_template_custom.tex
endif

# fill reference info
sed -i 's/dist_norm)/distnorm)/g' full_template_custom.tex
sed -i 's/GENOME_BUILD/'${genome}'/g' full_template_custom.tex
sed -i 's/COMP_BINSIZE/'${compBinSize}'/g' full_template_custom.tex
sed -i 's/RESOLUTION/'${binsize}'/g' full_template_custom.tex

#### MAKE REPORT/PRESENTATION ####
cd ..
set title = `cd ..; pwd | sed 's/.*\///'`
cat $report/full_template_custom.tex | sed "s/____PROJECT-TITLE_____/$title/g" >! report.tex
pdflatex -interaction nonstopmode -file-line-error report.tex
bibtex report.aux
pdflatex -interaction nonstopmode -file-line-error report.tex
pdflatex -interaction nonstopmode -file-line-error report.tex
rm -rf report.{bbl,blg,nav,out,aux,log,ps,dvi,snm,toc,tex}
rm -f $report/*.tex

#### ORGANIZE DATA/FILES ####
mkdir "${report}"/report-figures
mkdir "${report}"/report-figures/domains-diff
mv $report/*.png $report/report-figures/
mv $report/*.pdf $report/report-figures/
mv report.pdf $report/
cp -r $report/domains-diff/* $report/report-figures/domains-diff/
rm -f $report/report-figures/domains-diff/*/*/*/*.tsv $report/report-figures/domains-diff/*/*/*/*.bed
rm -f $report/domains-diff//*/*/*/*pdf $report/domains-diff//*/*/*/*png $report/domains-diff/*/*/*/template_intraTAD.tex

if ("$standard" == "TRUE") then
mkdir $report/report-figures/compartments-densityPlots-by-sample $report/report-figures/compartments-hexbinPlots-by-sample
mkdir $report/report-figures/compartments-densityPlots-by-group  $report/report-figures/compartments-hexbinPlots-by-group 
cp $report/compartments-stats-by-sample/density_plots/* $report/report-figures/compartments-densityPlots-by-sample/
cp $report/compartments-stats-by-group/density_plots/* $report/report-figures/compartments-densityPlots-by-group/
cp $report/compartments-stats-by-sample/hexbin_plots/* $report/report-figures/compartments-hexbinPlots-by-sample/
cp $report/compartments-stats-by-group/hexbin_plots/* $report/report-figures/compartments-hexbinPlots-by-group/
endif

endif

#########################################################################################
#                                  MAIN ABOVE BELOW                                     #
#########################################################################################

#### TRANSFER REPORT & DATA TO AN EXTERNAL GDRIVE ACCOUNT ####
if ($transferGdrive == "TRUE") then
echo "Transfering report data to: "$gdrive_remote""
	module unload r
	module load rclone
	rclone copy -P -L --exclude-from report-repo/exclude_files.txt $report $gdrive_remote
	module unload rclone
endif

#### TRANSFER REPORT MAIN DATA TO AN EXTERNAL HPC DIRECTORY #### (only for ABL employees with special HPC permissions)
if ($transferExternal == "TRUE") then
echo "Transfering report data to: /gpfs/data/sequence/results/external/NYU/ABL-HiC-reports/"$user"/"$report""
	module unload r
        module load rclone
        rclone copy -P -L --exclude-from report-repo/exclude_files.txt $report /gpfs/data/sequence/results/external/NYU/ABL-HiC-reports/"$user"/"$report"
        module unload rclone
chmod -R 775 /gpfs/data/sequence/results/external/NYU/ABL-HiC-reports/"$user"/"$report"
endif
